#!/usr/bin/env bash
# make brew-formula VERSION=v0.4.0
# Hashes come from the release's own SHA256SUMS, never from a human: a hash nobody generated is a hash nobody checked.
# The formula ships prebuilt archives, so installing needs no Go; a homebrew-core submission would have to be source based instead, since core builds its own bottles.
set -euo pipefail

version="${1:-}"
if [ -z "$version" ]; then
	echo "usage: make brew-formula VERSION=vX.Y.Z" >&2
	exit 2
fi
case "$version" in
v*) ;;
*)
	echo "version must start with v, got $version" >&2
	exit 2
	;;
esac

repo="noelruault/lazyaws"
dist="dist"
sums="$dist/SHA256SUMS"
out="$dist/lazyaws.rb"

mkdir -p "$dist"

# Prefer the published release's checksums, so the formula describes what people will actually download.
# Fall back to a local SHA256SUMS for a dry run before the release exists.
if gh release view "$version" --repo "$repo" >/dev/null 2>&1; then
	gh release download "$version" --repo "$repo" --pattern SHA256SUMS --output "$sums" --clobber
	echo "using SHA256SUMS from the $version release"
elif [ -f "$sums" ]; then
	echo "using local $sums (no $version release published yet)"
else
	echo "no $version release and no $sums; run make release-all first" >&2
	exit 1
fi

# sha_for prints the hash for one platform's archive, and fails loudly rather than emitting an empty string:
# a formula with a blank sha256 installs nothing and reports a checksum mismatch that names no cause.
sha_for() {
	local goos="$1" goarch="$2" name hash
	name="lazyaws-$version-$goos-$goarch.tar.gz"
	hash="$(awk -v want="$name" '$2 == want || $2 == "*" want { print $1 }' "$sums" | head -1)"
	if [ -z "$hash" ]; then
		echo "no checksum for $name in $sums" >&2
		exit 1
	fi
	printf '%s' "$hash"
}

darwin_arm64="$(sha_for darwin arm64)"
darwin_amd64="$(sha_for darwin amd64)"
linux_arm64="$(sha_for linux arm64)"
linux_amd64="$(sha_for linux amd64)"

base="https://github.com/$repo/releases/download/$version"
stripped="${version#v}"

cat >"$out" <<FORMULA
# Generated by scripts/brew-formula.sh in noelruault/lazyaws; edit that script, not this file.
# Regenerate with \`make brew-formula VERSION=<tag>\`, so the hashes keep coming from the release's own SHA256SUMS.
class Lazyaws < Formula
  desc "Keyboard-driven terminal UI for AWS"
  homepage "https://github.com/$repo"
  version "$stripped"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/lazyaws-$version-darwin-arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$base/lazyaws-$version-darwin-amd64.tar.gz"
      sha256 "$darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$base/lazyaws-$version-linux-arm64.tar.gz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$base/lazyaws-$version-linux-amd64.tar.gz"
      sha256 "$linux_amd64"
    end
  end

  def install
    bin.install "lazyaws"

    # A Homebrew install is a redistribution, so the notices MIT and BSD-3-Clause require travel with the binary.
    pkgshare.install "ACKNOWLEDGMENTS.md", "LICENSES", "third_party_licenses"
    doc.install "README.md", "SECURITY.md"
  end

  def caveats
    <<~EOS
      lazyaws reads your AWS profiles from ~/.aws/config. For an IAM Identity Center (SSO) setup, log in first:

        aws sso login --sso-session <your-session>

      Navigation: hjkl or the arrows to move, Tab to change panel, Enter to look into a resource,
      "," and "." for the detail tabs, and "?" for every key the focused panel answers to.
      If you would rather have vim, emacs or lazydocker keys: lazyaws --keymap=vim
    EOS
  end

  test do
    assert_match "lazyaws", shell_output("#{bin}/lazyaws -version")

    # A TUI cannot be driven from brew test, so -keymap stands in as the deepest non-interactive path.
    assert_match "keymap:", shell_output("#{bin}/lazyaws -keymap")
  end
end
FORMULA

echo "wrote $out"
